import sqlite3

DB_PATH = "app.db"

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

#We first create a table if it does not exist already, its schema consists of an id, medications a and b which are strings
# and the severity and description of the interaction between the two medications which are also strings

cur.execute("""
CREATE TABLE IF NOT EXISTS rules (
    id TEXT PRIMARY KEY,
    a  TEXT NOT NULL,
    b  TEXT NOT NULL,
    severity TEXT NOT NULL,
    description TEXT NOT NULL
);
""")

#In the following code we create a unique index on the pair of medications in a way that is independent of their order

cur.execute("""
CREATE UNIQUE INDEX IF NOT EXISTS ux_rules_pair
ON rules(
    CASE WHEN a < b THEN a ELSE b END,
    CASE WHEN a < b THEN b ELSE a END
);
""")

#We need to ensure that the pairs of medications will be trimmed and all in lowercase, and in alphabetical order
# so we don't have duplicates like ibuprofen_aspirin and aspirin_ibuprofen


def canon(a: str, b: str):
    a = a.strip().lower()
    b = b.strip().lower()
    return (a, b) if a <= b else (b, a)

seed_rules = [
    ("ibuprofen_aspirin", "ibuprofen", "aspirin", "major",
    "Talk to your doctor before using aspirin together with ibuprofen. Frequent or regular use of ibuprofen may reduce the effectiveness of aspirin if you are taking it to prevent heart attacks or strokes. In addition, combining these medications may increase your risk of developing gastrointestinal ulcers and bleeding. You may need a dose adjustment or more frequent monitoring by your doctor to safely use both medications. Contact your doctor immediately if you develop severe abdominal pain, bloating, sudden dizziness or lightheadedness, nausea, vomiting (especially with blood), loss of appetite, and/or black, tarry stools. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("ethanol_acetaminophen", "ethanol", "acetaminophen", "major", "Ask your doctor before using acetaminophen together with ethanol (alcohol). This can cause serious side effects that affect your liver. Call your doctor immediately if you experience a fever, chills, joint pain or swelling, excessive tiredness or weakness, unusual bleeding or bruising, skin rash or itching, loss of appetite, nausea, vomiting, or yellowing of the skin or the whites of your eyes. If your doctor does prescribe these medications together, you may need a dose adjustment or special tests to safely take both medications. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("azithromycin_zoloft", "azithromycin", "zoloft", "moderate", "Using azithromycin together with sertraline can increase the risk of an irregular heart rhythm that may be serious and potentially life-threatening, although it is a relatively rare side effect. You may be more susceptible if you have a heart condition called congenital long QT syndrome, other cardiac diseases, conduction abnormalities, or electrolyte disturbances (for example, magnesium or potassium loss due to severe or prolonged diarrhea or vomiting). Talk to your doctor if you have any questions or concerns. You should seek immediate medical attention if you develop sudden dizziness, lightheadedness, fainting, shortness of breath, or heart palpitations during treatment with these medications, whether together or alone. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("azithromycin_ondansetron", "azithromycin", "ondansetron", "moderate", "Using azithromycin together with ondansetron can increase the risk of an irregular heart rhythm that may be serious and potentially life-threatening, although it is a relatively rare side effect. You may be more susceptible if you have a heart condition called congenital long QT syndrome, other cardiac diseases, conduction abnormalities, or electrolyte disturbances (for example, magnesium or potassium loss due to severe or prolonged diarrhea or vomiting). Talk to your doctor if you have any questions or concerns. You should seek immediate medical attention if you develop sudden dizziness, lightheadedness, fainting, shortness of breath, or heart palpitations during treatment with these medications, whether together or alone. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("prednisone_aspirin", "prednisone", "aspirin", "moderate", "Using aspirin together with predniSONE may increase the risk of side effects in the gastrointestinal tract such as inflammation, bleeding, ulceration, and rarely, perforation. Gastrointestinal perforation is a potentially fatal condition and medical emergency where a hole forms all the way through the stomach or intestine. You should take these medications with food to lessen the risk. In addition, steroid medications like predniSONE have been reported to decrease the blood levels of aspirin and similar drugs in some cases, which may make them less effective in treating your condition. On the other hand, if you have been receiving both medications and predniSONE is stopped, blood levels of aspirin may subsequently increase and a dosage reduction may be required to avoid toxicity. Talk to your doctor if you have any questions or concerns. You may need a dose adjustment or more frequent monitoring by your doctor to safely use both medications. Your doctor may also be able to recommend medications to help protect the stomach and intestine if you are at high risk for developing serious gastrointestinal complications. You should seek immediate medical attention if you experience any unusual bleeding or bruising, or have other signs and symptoms of bleeding such as dizziness; lightheadedness; red or black, tarry stools; coughing up or vomiting fresh or dried blood that looks like coffee grounds; severe headache; and weakness. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("prednisone_xanax", "prednisone", "xanax", "minor", "Certain corticosteroids may decrease the plasma concentration of some benzodiazepines. Limited data are available for midazolam and triazolam. The mechanism is related to induction of hepatic cytochrome P450 enzymes responsible for benzodiazepine metabolism. The clinical significance may depend on the dosage and duration of corticosteroid therapy and be of greater importance with oral administration of benzodiazepines"),
    ("prednisone_vitamind3", "prednisone", "vitaminD3", "moderate", "PredniSONE may reduce the effects of cholecalciferol. You may require increased monitoring and/or an adjustment in the dosing of cholecalciferol to safely use this combination. Speak with your healthcare provider if you have any questions or concerns. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("prednisone_insulin", "prednisone", "insulin", "moderate", "PredniSONE may interfere with blood glucose control and reduce the effectiveness of insulin and other diabetic medications. Monitor your blood sugar levels closely. You may need a dose adjustment of your diabetic medications during and after treatment with predniSONE. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("insulin_aspirin", "insulin", "aspirin", "moderate", "Using aspirin together with insulin or certain other diabetes medications may increase the risk of hypoglycemia, or low blood sugar. Symptoms of hypoglycemia include headache, dizziness, drowsiness, nervousness, confusion, tremor, nausea, hunger, weakness, perspiration, palpitation, and rapid heartbeat. Talk to your doctor if you have any questions or concerns. You may need a dose adjustment or more frequent monitoring of your blood sugar to safely use both medications. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("insulin_lexapro", "insulin", "lexapro", "moderate", "Using escitalopram (Lexapro) together with insulin or certain other diabetes medications may increase the risk of hypoglycemia, or low blood sugar. Symptoms of hypoglycemia include headache, dizziness, drowsiness, nervousness, confusion, tremor, nausea, hunger, weakness, perspiration, palpitation, and rapid heartbeat. Talk to your doctor if you have any questions or concerns. You may need a dose adjustment or more frequent monitoring of your blood sugar to safely use both medications. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("tylenol_warfarin", "tylenol", "warfarin", "moderate", "Using acetaminophen together with warfarin is generally considered safe. However, the risk for bleeding may increase if higher dosages of acetaminophen (more than 1300 mg/day) are used for more than a few days at a time, especially in individuals who are elderly, consume alcohol regularly, or have poor nutrition. Talk to your doctor if you have any questions or concerns. Your doctor may be able to prescribe alternatives that do not interact, or you may need a dose adjustment or more frequent monitoring of your INR to safely use both medications. Many over-the-counter and prescription drug products used for the treatment of cough and cold, flu, pain, fever, arthritis, or headache may contain acetaminophen. To avoid inadvertently taking too much acetaminophen, you should check the ingredients of all the medications you take or intend to take. Consult a healthcare professional if you are not sure if a drug product contains acetaminophen, or if you need help figuring out what products are safe for you to use. You should seek immediate medical attention if you experience any unusual bleeding or bruising, or have other signs and symptoms of bleeding such as dizziness; lightheadedness; red or black, tarry stools; coughing up or vomiting fresh or dried blood that looks like coffee grounds; severe headache; and weakness. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("voltaren_warfarin", "voltaren", "warfarin", "major", "Using warfarin together with diclofenac may increase the risk of serious bleeding complications, especially in the gastrointestinal tract. Talk to your doctor if you have any questions or concerns. Your doctor may be able to prescribe alternatives that do not interact, or you may need a dose adjustment or more frequent monitoring of your INR to safely use both medications. You should seek immediate medical attention if you experience any unusual bleeding or bruising, or have other signs and symptoms of bleeding such as dizziness; lightheadedness; red or black, tarry stools; coughing up or vomiting fresh or dried blood that looks like coffee grounds; severe headache; and weakness. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("lexapro_warfarin", "lexapro", "warfarin", "moderate", "Using escitalopram together with warfarin may increase the risk of bleeding. The interaction may be more likely if you are elderly or have kidney or liver disease. Talk to your doctor if you have any questions or concerns. Your doctor may already be aware of the risks, but has determined that this is the best course of treatment for you and has taken appropriate precautions and is monitoring you closely for any potential complications. You should seek immediate medical attention if you experience any unusual bleeding or bruising, or have other signs and symptoms of bleeding such as dizziness; lightheadedness; red or black, tarry stools; coughing up or vomiting fresh or dried blood that looks like coffee grounds; severe headache; and weakness. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("benadryl_lorazepam", "benadryl", "lorazepam", "moderate", "Using LORazepam together with diphenhydrAMINE may increase side effects such as dizziness, drowsiness, confusion, and difficulty concentrating. Some people, especially the elderly, may also experience impairment in thinking, judgment, and motor coordination. You should avoid or limit the use of alcohol while being treated with these medications. Also avoid activities requiring mental alertness such as driving or operating hazardous machinery until you know how the medications affect you. Talk to your doctor if you have any questions or concerns. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("lorazepam_lexapro", "lorazepam", "lexapro", "minor", "Using LORazepam together with escitalopram may increase side effects such as dizziness, drowsiness, confusion, and difficulty concentrating. Some people, especially the elderly, may also experience impairment in thinking, judgment, and motor coordination. You should avoid or limit the use of alcohol while being treated with these medications. Also avoid activities requiring mental alertness such as driving or operating hazardous machinery until you know how the medications affect you. Talk to your doctor if you have any questions or concerns. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor."),
    ("lorazepam_zoloft", "lorazepam", "zoloft", "moderate", "Using LORazepam together with sertraline may increase side effects such as dizziness, drowsiness, confusion, and difficulty concentrating. Some people, especially the elderly, may also experience impairment in thinking, judgment, and motor coordination. You should avoid or limit the use of alcohol while being treated with these medications. Also avoid activities requiring mental alertness such as driving or operating hazardous machinery until you know how the medications affect you. Talk to your doctor if you have any questions or concerns. It is important to tell your doctor about all other medications you use, including vitamins and herbs. Do not stop using any medications without first talking to your doctor.")
]

rows = []
for id_, A, B, sev, desc in seed_rules:
    a, b = canon(A, B)
    rows.append((id_, a, b, sev, desc))

cur.executemany("INSERT OR REPLACE INTO rules (id,a,b,severity,description) VALUES (?,?,?,?,?)", rows)

conn.commit()
conn.close()

print(f"app.db is ready.")
